<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ComVenda extends \Application\Entity\ComVenda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'pkVenda', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'CadCliente', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhabertura', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhfechamento', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhcancelamento', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhultalteracao');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'pkVenda', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'CadCliente', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhabertura', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhfechamento', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhcancelamento', '' . "\0" . 'Application\\Entity\\ComVenda' . "\0" . 'dhultalteracao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ComVenda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkVenda()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkVenda();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkVenda', array());

        return parent::getPkVenda();
    }

    /**
     * {@inheritDoc}
     */
    public function getCadCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCadCliente', array());

        return parent::getCadCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function getDhabertura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDhabertura', array());

        return parent::getDhabertura();
    }

    /**
     * {@inheritDoc}
     */
    public function getDhfechamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDhfechamento', array());

        return parent::getDhfechamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getDhcancelamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDhcancelamento', array());

        return parent::getDhcancelamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getDhultalteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDhultalteracao', array());

        return parent::getDhultalteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setPkVenda($pkVenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPkVenda', array($pkVenda));

        return parent::setPkVenda($pkVenda);
    }

    /**
     * {@inheritDoc}
     */
    public function setCadCliente(\Application\Entity\CadCliente $CadCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCadCliente', array($CadCliente));

        return parent::setCadCliente($CadCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function setDhabertura(\DateTime $dhabertura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDhabertura', array($dhabertura));

        return parent::setDhabertura($dhabertura);
    }

    /**
     * {@inheritDoc}
     */
    public function setDhfechamento(\DateTime $dhfechamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDhfechamento', array($dhfechamento));

        return parent::setDhfechamento($dhfechamento);
    }

    /**
     * {@inheritDoc}
     */
    public function setDhcancelamento(\DateTime $dhcancelamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDhcancelamento', array($dhcancelamento));

        return parent::setDhcancelamento($dhcancelamento);
    }

    /**
     * {@inheritDoc}
     */
    public function setDhultalteracao(\DateTime $dhultalteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDhultalteracao', array($dhultalteracao));

        return parent::setDhultalteracao($dhultalteracao);
    }

}
