<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EstItem extends \Application\Entity\EstItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'PK_item', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'FK_grupo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'FK_unidade', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'FK_fabricante', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'dhCadastro', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'codigo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'xProd', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'marca', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'cor', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'NCM', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'cEAN', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'origem', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'quantidade', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'bloqueado', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'natureza', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'CST', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'custo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pIPI', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pST', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pDifAliquota', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pFrete', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'isentoPisCofins', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pDescMaximo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'vUnTrib');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'PK_item', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'FK_grupo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'FK_unidade', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'FK_fabricante', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'dhCadastro', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'codigo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'xProd', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'marca', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'cor', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'NCM', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'cEAN', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'origem', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'quantidade', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'bloqueado', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'natureza', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'CST', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'custo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pIPI', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pST', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pDifAliquota', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pFrete', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'isentoPisCofins', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'pDescMaximo', '' . "\0" . 'Application\\Entity\\EstItem' . "\0" . 'vUnTrib');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EstItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPK_item()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPK_item', array());

        return parent::getPK_item();
    }

    /**
     * {@inheritDoc}
     */
    public function getFK_grupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFK_grupo', array());

        return parent::getFK_grupo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFK_unidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFK_unidade', array());

        return parent::getFK_unidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getFK_fabricante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFK_fabricante', array());

        return parent::getFK_fabricante();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function getXProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXProd', array());

        return parent::getXProd();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', array());

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function getCor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCor', array());

        return parent::getCor();
    }

    /**
     * {@inheritDoc}
     */
    public function getNCM()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNCM', array());

        return parent::getNCM();
    }

    /**
     * {@inheritDoc}
     */
    public function getCEAN()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCEAN', array());

        return parent::getCEAN();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigem', array());

        return parent::getOrigem();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantidade', array());

        return parent::getQuantidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getBloqueado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloqueado', array());

        return parent::getBloqueado();
    }

    /**
     * {@inheritDoc}
     */
    public function getNatureza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNatureza', array());

        return parent::getNatureza();
    }

    /**
     * {@inheritDoc}
     */
    public function getCST()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCST', array());

        return parent::getCST();
    }

    /**
     * {@inheritDoc}
     */
    public function getCusto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCusto', array());

        return parent::getCusto();
    }

    /**
     * {@inheritDoc}
     */
    public function getPIPI()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPIPI', array());

        return parent::getPIPI();
    }

    /**
     * {@inheritDoc}
     */
    public function getPST()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPST', array());

        return parent::getPST();
    }

    /**
     * {@inheritDoc}
     */
    public function getPDifAliquota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDifAliquota', array());

        return parent::getPDifAliquota();
    }

    /**
     * {@inheritDoc}
     */
    public function getPFrete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPFrete', array());

        return parent::getPFrete();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsentoPisCofins()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsentoPisCofins', array());

        return parent::getIsentoPisCofins();
    }

    /**
     * {@inheritDoc}
     */
    public function getPDescMaximo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDescMaximo', array());

        return parent::getPDescMaximo();
    }

    /**
     * {@inheritDoc}
     */
    public function getVUnTrib()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVUnTrib', array());

        return parent::getVUnTrib();
    }

    /**
     * {@inheritDoc}
     */
    public function setPK_item($PK_item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPK_item', array($PK_item));

        return parent::setPK_item($PK_item);
    }

    /**
     * {@inheritDoc}
     */
    public function setFK_grupo($FK_grupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFK_grupo', array($FK_grupo));

        return parent::setFK_grupo($FK_grupo);
    }

    /**
     * {@inheritDoc}
     */
    public function setFK_unidade($FK_unidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFK_unidade', array($FK_unidade));

        return parent::setFK_unidade($FK_unidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setFK_fabricante($FK_fabricante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFK_fabricante', array($FK_fabricante));

        return parent::setFK_fabricante($FK_fabricante);
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function setXProd($xProd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXProd', array($xProd));

        return parent::setXProd($xProd);
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', array($marca));

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function setCor($cor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCor', array($cor));

        return parent::setCor($cor);
    }

    /**
     * {@inheritDoc}
     */
    public function setNCM($NCM)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNCM', array($NCM));

        return parent::setNCM($NCM);
    }

    /**
     * {@inheritDoc}
     */
    public function setCEAN($cEAN)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCEAN', array($cEAN));

        return parent::setCEAN($cEAN);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigem($origem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigem', array($origem));

        return parent::setOrigem($origem);
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantidade($quantidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantidade', array($quantidade));

        return parent::setQuantidade($quantidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setBloqueado($bloqueado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBloqueado', array($bloqueado));

        return parent::setBloqueado($bloqueado);
    }

    /**
     * {@inheritDoc}
     */
    public function setNatureza($natureza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNatureza', array($natureza));

        return parent::setNatureza($natureza);
    }

    /**
     * {@inheritDoc}
     */
    public function setCST($CST)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCST', array($CST));

        return parent::setCST($CST);
    }

    /**
     * {@inheritDoc}
     */
    public function setCusto($custo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCusto', array($custo));

        return parent::setCusto($custo);
    }

    /**
     * {@inheritDoc}
     */
    public function setPIPI($pIPI)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPIPI', array($pIPI));

        return parent::setPIPI($pIPI);
    }

    /**
     * {@inheritDoc}
     */
    public function setPST($pST)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPST', array($pST));

        return parent::setPST($pST);
    }

    /**
     * {@inheritDoc}
     */
    public function setPDifAliquota($pDifAliquota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPDifAliquota', array($pDifAliquota));

        return parent::setPDifAliquota($pDifAliquota);
    }

    /**
     * {@inheritDoc}
     */
    public function setPFrete($pFrete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPFrete', array($pFrete));

        return parent::setPFrete($pFrete);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsentoPisCofins($isentoPisCofins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsentoPisCofins', array($isentoPisCofins));

        return parent::setIsentoPisCofins($isentoPisCofins);
    }

    /**
     * {@inheritDoc}
     */
    public function setPDescMaximo($pDescMaximo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPDescMaximo', array($pDescMaximo));

        return parent::setPDescMaximo($pDescMaximo);
    }

    /**
     * {@inheritDoc}
     */
    public function setVUnTrib($vUnTrib)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVUnTrib', array($vUnTrib));

        return parent::setVUnTrib($vUnTrib);
    }

}
